replicaCount: 2
environment: dev

image:
  repository: 952429021322.dkr.ecr.ap-southeast-1.amazonaws.com/devopslite-be
  tag: v0.0.4
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::952429021322:role/devopslite_dev_eks_cluster_postgresql_sa_role

secretStore:
  region: ap-southeast-1
  create: true
  name: "secretstore-backend"

externalSecret:
  create: true
  name: "externalsecret-backend"

secret:
  name: backend

configmap:
  name: backend
  items:
    PORT: 80

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  backendProtocol: HTTP
  certificateArn: arn:aws:acm:ap-southeast-1:952429021322:certificate/eb93366d-2d7b-499c-b6f2-9b06243cad5d
  groupName: ingress
  groupOrder: "3"
  hosts:
    - host: api.dev.devopslite.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                number: 80
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 125Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: backend
        topologyKey: "kubernetes.io/hostname"
