postgresql:
  image:
    repository: postgres
    tag: 17.2
  persistence:
    size: 10Gi
    storageClass: gp2
  replica:
    replicaCount: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m
  service:
    type: ClusterIP
    port: 5432

serviceAccount:
  enabled: false
  name: postgresql-sa

secretStore:
  region: ap-southeast-1
  create: true
  name: secretstore-postgresql

externalSecret:
  create: true
  name: externalsecret-postgresql

secret:
  name: postgresql
