apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}-config
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configmap.items }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
