---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secret
  namespace: {{ .Values.argoNamespace | default "argocd" }}

spec:
  generators:
    - list:
        elements:
          {{ toYaml .Values.serversList | nindent 8 }}

  template:
    metadata:
      name: external-secret-{{ .Values.environment }}-{{`{{name}}`}}
      namespace: {{ .Values.argoNamespace | default "argocd" }}
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        server: {{"'{{server}}'"}}
        namespace: external-secret
      env: {{ .Values.environment }}
      project: {{ .Values.project }}
      syncPolicy:
        {{ toYaml .Values.syncPolicy | nindent 8 }}
      source:
        path: infra-components/external-secrets
        repoURL: {{ .Values.spec.source.repoURL }}
        targetRevision: {{ .Values.spec.source.targetRevision }}
        helm:
          valueFiles:
            - values.yaml
          releaseName: external-secret
