apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secret
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-secret
    server: in-cluster
  project: dev
  source:
    path: infra-components/external-secrets
    repoURL: https://github.com/dungpham91/devops.demo.argocd
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
