---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: eksctl.io/v1alpha5
kind: ExternalSecret
metadata:
  name: external-secrets
  namespace: postgres
spec:
  backendType: secretsManager
  data:
    - secretKey: postgres-password
      remoteRef:
        key: devopslite/postgres
        version: "1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: dev
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "latest"
    chart: postgresql
    helm:
      parameters:
        - name: global.postgresql.postgresqlDatabase
          value: "btc_data"
        - name: global.postgresql.postgresqlUsername
          value: "postgres"
        - name: global.postgresql.postgresqlPassword
          values: |
            postgresqlPassword:
              valueFrom:
                secretKeyRef:
                  name: external-secrets
                  key: postgres-password
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
