{{- if .Values.externalSecret.create -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
spec:
  refreshInterval: 1h 
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.secretStore.name }}
  target:
    name: {{ .Values.secret.name }}
  dataFrom:
  - extract:
      key: devopslite/postgresql
{{- end }}
