apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: postgresql-external-secret
spec:
  secretStoreRef:
    name: postgresql-secret
  target:
    name: postgresql-secret
  data:
    - secretKey: username
      remoteRef:
        key: devopslite/postgresql
        property: username
    - secretKey: password
      remoteRef:
        key: devopslite/postgresql
        property: password
    - secretKey: dbname
      remoteRef:
        key: devopslite/postgresql
        property: dbname
