apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: postgresql-secret
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: postgresql-sa
