apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretStore
metadata:
  name: postgresql-secret
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: devopslite/postgresql
        objectType: Secret
