apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  serviceName: postgresql
  replicas: {{ .Values.postgresql.replica.replicaCount }}
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: postgresql
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: {{ .Values.postgresql.resources.requests.memory }}
              cpu: {{ .Values.postgresql.resources.requests.cpu }}
            limits:
              memory: {{ .Values.postgresql.resources.limits.memory }}
              cpu: {{ .Values.postgresql.resources.limits.cpu }}
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgresql.persistence.size }}
        storageClassName: {{ .Values.postgresql.persistence.storageClass }}
